name: aacuf
version: '1.0'
main: com.gilbertomorales.aacuf.Main
author: 'Gilberto Morales'
api-version: '1.21'
commands:
  tp:
    description: Teleporta para um jogador.
    usage: /tp <jogador>
  tphere:
    description: Teleporta um jogador até você.
    usage: /tphere <jogador>
  tpall:
    description: Teleporta todos os jogadores até você.
    usage: /tpall
  kick:
    description: Expulsar um jogador do servidor.
    usage: /kick <jogador> [motivo]
  givecoletor:
    description: Envia um coletor de chunk
    usage: /givecoletor <jogador>
    permission: aacuf.coletor.give
    permission-message: Sem permissão.
  removercoletores:
    description: Remove coletores em um raio de 3 blocos ao redor do jogador.
    usage: /removercoletores
    permission: aacuf.coletor.remover
